In [1]:
import requests
import pandas as pd

In [4]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7e785003980a9755a14b564494253538&language=en-US&page=1')

In [15]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [20]:
temp_df.shape

(20, 7)

In [16]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,314.3613,8.973,1406
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,73.6464,8.721,30409
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,49.9302,8.687,22947
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,371.0794,8.634,4155
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.6549,8.571,13910

In [17]:
df = pd.DataFrame()

In [19]:
for i in range(1,544):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7e785003980a9755a14b564494253538&language=en-US&page=1')
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [21]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,314.3613,8.973,1406
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,73.6464,8.721,30409
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,49.9302,8.687,22947
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,371.0794,8.634,4155
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.6549,8.571,13910
...,...,...,...,...,...,...,...
10855,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,36.3520,8.484,30195
10856,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,30.4337,8.479,12556
10857,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,78.7304,8.475,39815
10858,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,21.4717,8.470,9628
10859,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,31.4936,8.465,29743

In [22]:
df.shape

(10860, 7)

In [23]:
df.to_csv('movies.csv')